example R: introduction
ldorau/2021-04-21.web pull request #13
Opened 2021-10-28 12:26 UTC by janekmi

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ldorau/2021-04-21.web/13)

2021-10-28 13:03 UTC, ldorau requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/13)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[templates/examples/R/body.tmpl, line 24 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/13#-Mn5ygCD1h1rwRUyPbvP:-Mn5ygCD1h1rwRUyPbvQ:b-15fg16) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/9a68e3f89d08caecee1de7ef29d1ddd52de33616/templates/examples/R/body.tmpl#L24)):*
> ```
> understand despite PMEM and RPMEM both making use
> ```

understand **that** despite PMEM and RPMEM both **are** making use
___
*[templates/examples/R/body.tmpl, line 24 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/13#-Mn5ytdK4B7dhyWbjOpe:-Mn5ytdK4B7dhyWbjOpf:bb3cvrh) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/9a68e3f89d08caecee1de7ef29d1ddd52de33616/templates/examples/R/body.tmpl#L24)):*
> ```
>  RPMEM access Persistent Memory
> ```

 RPMEM access**es** Persistent Memory
___
*[templates/examples/R/body.tmpl, line 24 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/13#-Mn5z3uzCHJvCR7uI4IQ:-Mn5z3uzCHJvCR7uI4IR:bpwc71o) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/9a68e3f89d08caecee1de7ef29d1ddd52de33616/templates/examples/R/body.tmpl#L24)):*
> ```
> slower compared to 
> ```

slower compar**ing** to 


<!-- Sent from Reviewable.io -->

2021-10-28 13:12 UTC, osalyk reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/13)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @janekmi, @ldorau, and @osalyk)



<!-- Sent from Reviewable.io -->

2021-10-28 13:23 UTC, ldorau requested changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/13)* status: all files reviewed, 12 unresolved discussions (waiting on @janekmi)

___
*[templates/examples/R/body.tmpl, line 27 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/13#-Mn61wdrBlUp-4WhCgvE:-Mn61wdrBlUp-4WhCgvF:bbiug1g) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/9a68e3f89d08caecee1de7ef29d1ddd52de33616/templates/examples/R/body.tmpl#L27)):*
> ```
> I will guide you
> ```

**We** will guide you
___
*[templates/examples/R/body.tmpl, line 27 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/13#-Mn621FZA9FtahIsBjHV:-Mn621F_3wtfQhmg7J7u:b-z5q1zo) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/9a68e3f89d08caecee1de7ef29d1ddd52de33616/templates/examples/R/body.tmpl#L27)):*
> ```
> I will show you
> ```

**We** will show you
___
*[templates/examples/R/body.tmpl, line 27 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/13#-Mn6296a6FfIdqmzWgVw:-Mn6296a6FfIdqmzWgVx:bth9zdj) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/9a68e3f89d08caecee1de7ef29d1ddd52de33616/templates/examples/R/body.tmpl#L27)):*
> ```
> using a librpma library
> ```

using **the** librpma library (is there any other librpma library ?)
___
*[templates/examples/R/body.tmpl, line 30 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/13#-Mn62TWV8Lusfx0SZDnr:-Mn62TWV8Lusfx0SZDns:brrd2kq) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/9a68e3f89d08caecee1de7ef29d1ddd52de33616/templates/examples/R/body.tmpl#L30)):*
> ```
> you will:
> ```

you will **know/learn**:  ?
___
*[templates/examples/R/body.tmpl, line 32 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/13#-Mn62imi6Mt3P271T5aJ:-Mn62imi6Mt3P271T5aK:bs7gq0a) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/9a68e3f89d08caecee1de7ef29d1ddd52de33616/templates/examples/R/body.tmpl#L32)):*
> ```
> and what is good for
> ```

and what **it** is good for
___
*[templates/examples/R/body.tmpl, line 33 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/13#-Mn62t0K3iqNZ3Cx5Ivx:-Mn62t0K3iqNZ3Cx5Ivy:bsst41i) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/9a68e3f89d08caecee1de7ef29d1ddd52de33616/templates/examples/R/body.tmpl#L33)):*
> ```
> compared to
> ```

compar**ing** to
___
*[templates/examples/R/body.tmpl, line 35 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/13#-Mn632eN4LsAFvbG-OmI:-Mn632eN4LsAFvbG-OmJ:b67l28e) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/9a68e3f89d08caecee1de7ef29d1ddd52de33616/templates/examples/R/body.tmpl#L35)):*
> ```
> how to verify the RDMA network works properly
> ```

how to verify **if** the RDMA network works properly
___
*[templates/examples/R/body.tmpl, line 54 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/13#-Mn63OLN3V_MvTVkOz9i:-Mn63OLN3V_MvTVkOz9j:b-sykafb) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/9a68e3f89d08caecee1de7ef29d1ddd52de33616/templates/examples/R/body.tmpl#L54)):*
> ```
> reading remote system's memory and write its back
> ```

reading remote system's memory and writ**ing it** back
___
*[templates/examples/R/body.tmpl, line 54 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/13#-Mn63W4R5DuiqtwXTwAZ:-Mn63W4R5DuiqtwXTwA_:bos1z13) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/9a68e3f89d08caecee1de7ef29d1ddd52de33616/templates/examples/R/body.tmpl#L54)):*
> ```
> in a persistent manner
> ```

in **the** persistent manner


<!-- Sent from Reviewable.io -->

2021-10-29 18:20 UTC, grom72 reviewed
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/13)* status: all files reviewed, 16 unresolved discussions (waiting on @janekmi)

___
*[templates/examples/R/body.tmpl, line 4 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/13#-MnCEW8nDacguwGnp_iT:-MnCEW8nDacguwGnp_iU:b-2p4r8b) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/9a68e3f89d08caecee1de7ef29d1ddd52de33616/templates/examples/R/body.tmpl#L4)):*
> ```
> RPMEM
> ```
RPMem  
......
___
*[templates/examples/R/body.tmpl, line 4 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/13#-MnCEne_1xZxqx0U2tnB:-MnCEne_1xZxqx0U2tnC:b1si9rb) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/9a68e3f89d08caecee1de7ef29d1ddd52de33616/templates/examples/R/body.tmpl#L4)):*
> ```
> network
> ```
technology
___
*[templates/examples/R/body.tmpl, line 4 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/13#-MnCFf2WA-pD3oc1sbwm:-MnCFf2WA-pD3oc1sbwn:b-t1ybyj) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/9a68e3f89d08caecee1de7ef29d1ddd52de33616/templates/examples/R/body.tmpl#L4)):*
> ```
> Persistent Memory
> ```
Persistent Memory (or PMem for short)
___
*[templates/examples/R/body.tmpl, line 7 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/13#-MnCFB2zET6FKcDMs1g0:-MnCFB2zET6FKcDMs1g1:b-f5x5zq) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/9a68e3f89d08caecee1de7ef29d1ddd52de33616/templates/examples/R/body.tmpl#L7)):*
> ```
> You may ask why you even bother doing so? Why your application simply cannot run on the remote system where the already mentioned Persistent Memory is installed instead of on yet another system? Why complicate the solution?
> ```
Do we need this paragraph at all? It gives a bad impression about RPMem as something complicated, something not needed etc.


<!-- Sent from Reviewable.io -->

2021-11-02 16:54 UTC, janekmi reviewed
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/13)* status: 0 of 1 files reviewed, 16 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[templates/examples/R/body.tmpl, line 4 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/13#-MnCEW8nDacguwGnp_iT:-MnW7TY8E0x-06xCAB3w:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/9a68e3f89d08caecee1de7ef29d1ddd52de33616/templates/examples/R/body.tmpl#L4)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> RPMEM
> ```
RPMem  
......
</blockquote></details>

Done.
___
*[templates/examples/R/body.tmpl, line 4 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/13#-MnCEne_1xZxqx0U2tnB:-MnW7eG4BSzTxY6LLUpD:b-18o5lb) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/9a68e3f89d08caecee1de7ef29d1ddd52de33616/templates/examples/R/body.tmpl#L4)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> network
> ```
technology
</blockquote></details>

1. I'm not sure it is more specific. In your opinion it is?
2. Calling it a network introduces a familiar concept (namely networking) despite it being a specific type of networking. Still, it may allow the reader to relate their experience with what we are trying to introduce to them.
___
*[templates/examples/R/body.tmpl, line 4 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/13#-MnCFf2WA-pD3oc1sbwm:-MnW8vEI8hx-9T6ouZc_:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/9a68e3f89d08caecee1de7ef29d1ddd52de33616/templates/examples/R/body.tmpl#L4)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> Persistent Memory
> ```
Persistent Memory (or PMem for short)
</blockquote></details>

Done.
___
*[templates/examples/R/body.tmpl, line 7 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/13#-MnCFB2zET6FKcDMs1g0:-MnVmewd3E3l5pNq7ok7:b-b6mscl) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/9a68e3f89d08caecee1de7ef29d1ddd52de33616/templates/examples/R/body.tmpl#L7)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> You may ask why you even bother doing so? Why your application simply cannot run on the remote system where the already mentioned Persistent Memory is installed instead of on yet another system? Why complicate the solution?
> ```
Do we need this paragraph at all? It gives a bad impression about RPMem as something complicated, something not needed etc.
</blockquote></details>

I want to introduce to the reader when RPMem should enter their attention.
I think it is important to answer the "Why?" question.

Do you think it is not needed or do you want to rephrase it?
___
*[templates/examples/R/body.tmpl, line 24 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/13#-Mn5z3uzCHJvCR7uI4IQ:-MnWYPaVAjuyhk9D_gEH:br7w3mb) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/9a68e3f89d08caecee1de7ef29d1ddd52de33616/templates/examples/R/body.tmpl#L24)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> slower compared to 
> ```

slower compar**ing** to 
</blockquote></details>

Are you sure?

Ref: https://ell.stackexchange.com/questions/113706/compared-to-or-comparing-to
___
*[templates/examples/R/body.tmpl, line 24 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/13#-Mn5ygCD1h1rwRUyPbvP:-MnWZWn031gt6KAGK-5F:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/9a68e3f89d08caecee1de7ef29d1ddd52de33616/templates/examples/R/body.tmpl#L24)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> understand despite PMEM and RPMEM both making use
> ```

understand **that** despite PMEM and RPMEM both **are** making use
</blockquote></details>

Done.
___
*[templates/examples/R/body.tmpl, line 24 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/13#-Mn5ytdK4B7dhyWbjOpe:-MnWZYcXBQfHcIgSjgWm:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/9a68e3f89d08caecee1de7ef29d1ddd52de33616/templates/examples/R/body.tmpl#L24)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  RPMEM access Persistent Memory
> ```

 RPMEM access**es** Persistent Memory
</blockquote></details>

Done.
___
*[templates/examples/R/body.tmpl, line 27 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/13#-Mn6296a6FfIdqmzWgVw:-MnWYXDbCScIj0RMJzYI:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/9a68e3f89d08caecee1de7ef29d1ddd52de33616/templates/examples/R/body.tmpl#L27)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> using a librpma library
> ```

using **the** librpma library (is there any other librpma library ?)
</blockquote></details>

Done.
___
*[templates/examples/R/body.tmpl, line 30 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/13#-Mn62TWV8Lusfx0SZDnr:-MnWYe-r7dXl211NAFrC:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/9a68e3f89d08caecee1de7ef29d1ddd52de33616/templates/examples/R/body.tmpl#L30)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> you will:
> ```

you will **know/learn**:  ?
</blockquote></details>

Done.
___
*[templates/examples/R/body.tmpl, line 32 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/13#-Mn62imi6Mt3P271T5aJ:-MnWYhP69TlfJRa1bcF_:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/9a68e3f89d08caecee1de7ef29d1ddd52de33616/templates/examples/R/body.tmpl#L32)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> and what is good for
> ```

and what **it** is good for
</blockquote></details>

Done.
___
*[templates/examples/R/body.tmpl, line 33 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/13#-Mn62t0K3iqNZ3Cx5Ivx:-MnWYhoD3bO4xkOBsEHj:b3kqx) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/9a68e3f89d08caecee1de7ef29d1ddd52de33616/templates/examples/R/body.tmpl#L33)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> compared to
> ```

compar**ing** to
</blockquote></details>

.
___
*[templates/examples/R/body.tmpl, line 35 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/13#-Mn632eN4LsAFvbG-OmI:-MnWYqqe7tHMagOGeZux:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/9a68e3f89d08caecee1de7ef29d1ddd52de33616/templates/examples/R/body.tmpl#L35)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> how to verify the RDMA network works properly
> ```

how to verify **if** the RDMA network works properly
</blockquote></details>

Done.
___
*[templates/examples/R/body.tmpl, line 54 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/13#-Mn63OLN3V_MvTVkOz9i:-MnWZ-N-1ypc6fnw-PG0:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/9a68e3f89d08caecee1de7ef29d1ddd52de33616/templates/examples/R/body.tmpl#L54)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> reading remote system's memory and write its back
> ```

reading remote system's memory and writ**ing it** back
</blockquote></details>

Done.
___
*[templates/examples/R/body.tmpl, line 54 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/13#-Mn63W4R5DuiqtwXTwAZ:-MnWZ1VAC5_UX2O_ZBkQ:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/9a68e3f89d08caecee1de7ef29d1ddd52de33616/templates/examples/R/body.tmpl#L54)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> in a persistent manner
> ```

in **the** persistent manner
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-02 16:57 UTC, janekmi reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/13)* status: 0 of 1 files reviewed, 16 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[templates/examples/R/body.tmpl, line 27 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/13#-Mn61wdrBlUp-4WhCgvE:-MnW_KLH1jpTWQt9DvRO:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/9a68e3f89d08caecee1de7ef29d1ddd52de33616/templates/examples/R/body.tmpl#L27)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> I will guide you
> ```

**We** will guide you
</blockquote></details>

Done.
___
*[templates/examples/R/body.tmpl, line 27 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/13#-Mn621FZA9FtahIsBjHV:-MnW_L7uBipRC7IjoT3n:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/9a68e3f89d08caecee1de7ef29d1ddd52de33616/templates/examples/R/body.tmpl#L27)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> I will show you
> ```

**We** will show you
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-03 09:00 UTC, ldorau requested changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/13)* status: all files reviewed, 6 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[templates/examples/R/body.tmpl, line 24 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/13#-Mn5z3uzCHJvCR7uI4IQ:-MnZzY1L2Z2j1EpU3KnU:b-tyxd89) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/9a68e3f89d08caecee1de7ef29d1ddd52de33616/templates/examples/R/body.tmpl#L24)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Are you sure?

Ref: https://ell.stackexchange.com/questions/113706/compared-to-or-comparing-to
</blockquote></details>

Yes, I'm sure. It should be:

"they are still a few orders of magnitude slower **comparing** to ... "

or:

"they are still a few orders of magnitude slower **if/when they are compared** to  ..."
___
*[templates/examples/R/body.tmpl, line 33 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/13#-Mn62t0K3iqNZ3Cx5Ivx:-Mn_0QSK7DPs9AYenMWj:b3kqx) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/9a68e3f89d08caecee1de7ef29d1ddd52de33616/templates/examples/R/body.tmpl#L33)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

.


<!-- Sent from Reviewable.io -->

2021-11-03 09:13 UTC, janekmi reviewed
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/13)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[templates/examples/R/body.tmpl, line 24 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/13#-Mn5z3uzCHJvCR7uI4IQ:-Mn_3jVOD0Ukpv1qBq-Y:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/9a68e3f89d08caecee1de7ef29d1ddd52de33616/templates/examples/R/body.tmpl#L24)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Yes, I'm sure. It should be:

"they are still a few orders of magnitude slower **comparing** to ... "

or:

"they are still a few orders of magnitude slower **if/when they are compared** to  ..."


</blockquote></details>

Done.
___
*[templates/examples/R/body.tmpl, line 33 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/13#-Mn62t0K3iqNZ3Cx5Ivx:-Mn_3kGw3Nbxsvlx8vAA:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/9a68e3f89d08caecee1de7ef29d1ddd52de33616/templates/examples/R/body.tmpl#L33)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-03 09:22 UTC, ldorau approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/13)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72)



<!-- Sent from Reviewable.io -->

2021-11-03 09:22 UTC, ldorau approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/13#-:-Mn_5naOEVJ3PUziekIL:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72)



<!-- Sent from Reviewable.io -->

2021-11-03 09:34 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/13)* status: all files reviewed, 5 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[templates/examples/R/body.tmpl, line 3 at r4](https://reviewable.io/reviews/ldorau/2021-04-21.web/13#-Mn_8J6V7W5lFcy_CgTJ:-Mn_8J6W7osZ2XeaN1Zm:byfh7ii) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/37302650e614db65b3bea29887a26599e9a95e22/templates/examples/R/body.tmpl#L3)):*
> ```
> {{top "Remote Persistent Memory"}}
> 
> <p class="intro">
> ```

It should be aligned to the left as the rest of the text (not centered):

![1.jpg](https://files.reviewableusercontent.io/images/reviewable/8492895/PLHqNsLJE4-kQh4aRpyXWQRl/1.jpeg)


<!-- Sent from Reviewable.io -->

2021-11-03 09:36 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/13)* status: all files reviewed, 7 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[templates/examples/R/body.tmpl, line 12 at r4](https://reviewable.io/reviews/ldorau/2021-04-21.web/13#-Mn_8e_pCkw_cUVGgV6P:-Mn_8e_pCkw_cUVGgV6Q:bthz46e) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/37302650e614db65b3bea29887a26599e9a95e22/templates/examples/R/body.tmpl#L12)):*
> ```
> <li>
> ```

`</li>`
___
*[templates/examples/R/body.tmpl, line 16 at r4](https://reviewable.io/reviews/ldorau/2021-04-21.web/13#-Mn_8kUgCfNfkiHoVnKg:-Mn_8kUgCfNfkiHoVnKh:bb81ife) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/37302650e614db65b3bea29887a26599e9a95e22/templates/examples/R/body.tmpl#L16)):*
> ```
>     <li>redundancy<li>
>     <li>migrability<li>
>     <li>configurability<li>
> ```

.


<!-- Sent from Reviewable.io -->

2021-11-03 09:40 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/13)* status: all files reviewed, 8 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[templates/examples/R/body.tmpl, line 35 at r4](https://reviewable.io/reviews/ldorau/2021-04-21.web/13#-Mn_99ZN-qU-LG3IWfGp:-Mn_99ZN-qU-LG3IWfGq:b3epw4l) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/37302650e614db65b3bea29887a26599e9a95e22/templates/examples/R/body.tmpl#L35)):*
> ```
> properly<li>
> ```

.


<!-- Sent from Reviewable.io -->

2021-11-03 10:03 UTC, janekmi reviewed
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/13)* status: 0 of 1 files reviewed, 8 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[templates/examples/R/body.tmpl, line 3 at r4](https://reviewable.io/reviews/ldorau/2021-04-21.web/13#-Mn_8J6V7W5lFcy_CgTJ:-Mn_EI4NAN2ay_IBE8Tx:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/37302650e614db65b3bea29887a26599e9a95e22/templates/examples/R/body.tmpl#L3)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It should be aligned to the left as the rest of the text (not centered):

![1.jpg](https://files.reviewableusercontent.io/images/reviewable/8492895/PLHqNsLJE4-kQh4aRpyXWQRl/1.jpeg)

</blockquote></details>

Done.
___
*[templates/examples/R/body.tmpl, line 12 at r4](https://reviewable.io/reviews/ldorau/2021-04-21.web/13#-Mn_8e_pCkw_cUVGgV6P:-Mn_EZqVCB0eVIbkIfVy:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/37302650e614db65b3bea29887a26599e9a95e22/templates/examples/R/body.tmpl#L12)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> <li>
> ```

`</li>`
</blockquote></details>

Done.
___
*[templates/examples/R/body.tmpl, line 16 at r4](https://reviewable.io/reviews/ldorau/2021-04-21.web/13#-Mn_8kUgCfNfkiHoVnKg:-Mn_E_HR7ERFYoBM_XrY:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/37302650e614db65b3bea29887a26599e9a95e22/templates/examples/R/body.tmpl#L16)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>     <li>redundancy<li>
>     <li>migrability<li>
>     <li>configurability<li>
> ```

.
</blockquote></details>

Done.
___
*[templates/examples/R/body.tmpl, line 35 at r4](https://reviewable.io/reviews/ldorau/2021-04-21.web/13#-Mn_99ZN-qU-LG3IWfGp:-Mn_EvQY3uZIOZI9rx1n:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/37302650e614db65b3bea29887a26599e9a95e22/templates/examples/R/body.tmpl#L35)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> properly<li>
> ```

.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-03 10:13 UTC, ldorau requested changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/13)* status: all files reviewed, 5 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[templates/examples/R/body.tmpl, line 46 at r5](https://reviewable.io/reviews/ldorau/2021-04-21.web/13#-Mn_HD6w0AULHBqs9NO4:-Mn_HD6w0AULHBqs9NO5:b20vny4) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/6b1d02f2ed3a3e86878fd24cf3fbf91f89dca3c1/templates/examples/R/body.tmpl#L46)):*
> ```
> {{template "scrollToContinue"}}
> ```

Is it needed ?

![2.jpg](https://files.reviewableusercontent.io/images/reviewable/8492895/WL9-sJfvtykSJd97tascRlh8/2.jpeg)


<!-- Sent from Reviewable.io -->

2021-11-03 10:17 UTC, janekmi reviewed
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/13)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[templates/examples/R/body.tmpl, line 46 at r5](https://reviewable.io/reviews/ldorau/2021-04-21.web/13#-Mn_HD6w0AULHBqs9NO4:-Mn_I7bq2hqdWem0MNJx:bgijdj9) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/6b1d02f2ed3a3e86878fd24cf3fbf91f89dca3c1/templates/examples/R/body.tmpl#L46)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> {{template "scrollToContinue"}}
> ```

Is it needed ?

![2.jpg](https://files.reviewableusercontent.io/images/reviewable/8492895/WL9-sJfvtykSJd97tascRlh8/2.jpeg)

</blockquote></details>

You are right. Thank you for checking all of this hands-on!


<!-- Sent from Reviewable.io -->

2021-11-03 10:32 UTC, ldorau approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/13)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72)



<!-- Sent from Reviewable.io -->

2021-11-03 12:41 UTC, ldorau approved these changes
@grom72 ping

> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/13#-:-Mn_oQqgDLO1qwunOnuQ:bhcj54j)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72)



<!-- Sent from Reviewable.io -->

2021-11-03 13:47 UTC, grom72 reviewed
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/13)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[templates/examples/R/body.tmpl, line 4 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/13#-MnCEne_1xZxqx0U2tnB:-Mna1DiZEnNCQ-LaV891:b-1b10te) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/9a68e3f89d08caecee1de7ef29d1ddd52de33616/templates/examples/R/body.tmpl#L4)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

1. I'm not sure it is more specific. In your opinion it is?
2. Calling it a network introduces a familiar concept (namely networking) despite it being a specific type of networking. Still, it may allow the reader to relate their experience with what we are trying to introduce to them.
</blockquote></details>

Remote Direct Memory Access network does not sound OK.
___
*[templates/examples/R/body.tmpl, line 7 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/13#-MnCFB2zET6FKcDMs1g0:-Mn_DF0SEY6dVY9QKwZI:b-7hiwd1) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/9a68e3f89d08caecee1de7ef29d1ddd52de33616/templates/examples/R/body.tmpl#L7)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I want to introduce to the reader when RPMem should enter their attention.
I think it is important to answer the "Why?" question.

Do you think it is not needed or do you want to rephrase it?
</blockquote></details>

I think that it is tricky to give an argument to use RPMem as part of the hackathon. It could be a good material for a blog post or perhaps it will be better to have a link to some external materials.
The purpose of the hackathon is to answer the question: How to use RPMA? not Why use RPMA?


<!-- Sent from Reviewable.io -->

2021-11-03 18:38 UTC, grom72 reviewed
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/13)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2021-11-04 00:36 UTC, janekmi reviewed
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/13)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[templates/examples/R/body.tmpl, line 4 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/13#-MnCEne_1xZxqx0U2tnB:-MncMJTe-uTleAbrpf3t:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/9a68e3f89d08caecee1de7ef29d1ddd52de33616/templates/examples/R/body.tmpl#L4)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Remote Direct Memory Access network does not sound OK.
</blockquote></details>

Done.
___
*[templates/examples/R/body.tmpl, line 7 at r1](https://reviewable.io/reviews/ldorau/2021-04-21.web/13#-MnCFB2zET6FKcDMs1g0:-MncMKlz-FUWnu8wsa7e:bte28bv) ([raw file](https://github.com/ldorau/2021-04-21.web/blob/9a68e3f89d08caecee1de7ef29d1ddd52de33616/templates/examples/R/body.tmpl#L7)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

I think that it is tricky to give an argument to use RPMem as part of the hackathon. It could be a good material for a blog post or perhaps it will be better to have a link to some external materials.
The purpose of the hackathon is to answer the question: How to use RPMA? not Why use RPMA?
</blockquote></details>

Maybe it is just me. My first question would be: why should I care? xD
But assuming attendees will have some background or interest in this, I have dropped this part.


<!-- Sent from Reviewable.io -->

2021-11-04 07:37 UTC, ldorau approved these changes
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/13)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)



<!-- Sent from Reviewable.io -->

2021-11-04 07:43 UTC, grom72 reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/13#-:-MndtkuI6J7RP3W6N3gH:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2021-11-04 07:43 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21.web/13)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2021-11-04 07:44 UTC, merged